dist: jammy
os: linux
sudo: required
language: python

matrix:
    include:
        - python: '3.9'
          env:
            - COVERAGE="true"
            - RDMAV_FORK_SAFE=1

        - python: '3.10'
          env:
            - RDMAV_FORK_SAFE=1

        - python: '3.11'
          env:
            - RDMAV_FORK_SAFE=1

        - python: '3.12'
          env:
            - RDMAV_FORK_SAFE=1

        - python: '3.13'
          env:
            - RDMAV_FORK_SAFE=1

        - python: '3.14-dev'
          env:
            - CYTHON="true" # numpy source build
            - DILL="master"
            - RDMAV_FORK_SAFE=1

        - python: '3.15-dev'
          env:
            - CYTHON="true" # numpy source build
            - DILL="master"
            - RDMAV_FORK_SAFE=1

        - python: 'pypy3.9-7.3.15' # at 7.3.16
          env:
            - RDMAV_FORK_SAFE=1

        - python: 'pypy3.10-7.3.19'
          env:
            - RDMAV_FORK_SAFE=1

        - python: 'pypy3.11-7.3.20'
          env:
            - RDMAV_FORK_SAFE=1

    allow_failures:
        - python: '3.15-dev' # prerelease; CI missing
        - python: 'pypy3.11-7.3.20' # CI missing
    fast_finish: true

cache:
    pip: true
    apt: true

before_install:
    - set -e  # fail on any error
    - sudo apt-get update -q
    - set -x; sudo apt-get install -y -q g++ mpich libmpich-dev # openmpi-bin libopenmpi-dev
    - export MPICC=$(which mpicc)
    - if [[ $COVERAGE == "true" ]]; then pip install coverage; fi
    - if [[ $CYTHON == "true" ]]; then pip install "cython<0.29.25"; fi #FIXME
    - if [[ $DILL == "master" ]]; then pip install "https://github.com/uqfoundation/dill/archive/master.tar.gz"; fi

install:
    - python -m pip install --no-binary mpi4py mpi4py
    - python -m pip install .

script:
    - mpiexec -np 1 python examples/which.py
    - for test in pyina/tests/__init__.py; do echo $test ; if [[ $COVERAGE == "true" ]]; then coverage run -a $test > /dev/null; else python $test > /dev/null; fi ; done
    - for test in pyina/tests/test_*.py; do echo $test ; if [[ $COVERAGE == "true" ]]; then coverage run -a $test > /dev/null; else python $test > /dev/null; fi ; done

after_success:
    - if [[ $COVERAGE == "true" ]]; then bash <(curl -s https://codecov.io/bash); else echo ''; fi
    - if [[ $COVERAGE == "true" ]]; then coverage report; fi
